name: linter

on:
  push: # Execute on every push to the master branch. Merging a pull request counts as a push.
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
      - run: npm install -g dockerfilelint prettier@2.3.0
      - run: dockerfilelint Dockerfile
      - run: prettier --check .
